## CÁC THƯ VIỆN Pandas, Matplotlib, Starmodels,... ĐỀU DỰA VÀO NumPy


In [2]:
import numpy as np


In [3]:
# Cách convert 1 NumpyArray từ một Python List
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
# Python cho phép 1 list có nhiều kiểu dữ liệu
[3.4,5,6,7]

[3.4, 5, 6, 7]

In [6]:
# Nhưng NumPy thì không cho phép, np tự convert thành 1 kiểu dữ liệu
np.array([3.4, 5, 6, 7])

array([3.4, 5. , 6. , 7. ])

In [7]:
# Ép kiểu dữ liệu trong nparray
# str : np.array([list], dtype = (""))
np.array([3.4, 5, 6, 7],dtype = ("float32"))

array([3.4, 5. , 6. , 7. ], dtype=float32)

In [9]:
a = np.array([1,2,3,4])

In [10]:
type(a)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [15]:
type(a2)

numpy.ndarray

In [27]:
# NP có một thuộc tính để xem số chiều của mảng
a.ndim  #  1
a2.ndim  #  2
# Thuộc tính xem kiểu dữ liệu của các element bên trong
a2.dtype # dtype('int64')
# Thuộc tính count element trong array
a2.size # 6
# Thuộc tính trả về dòng, cột
a.shape # (2, 3)

(4,)

## Tạo NumPy Array từ Scratch
### zeros, ones, full, arange, linspace

In [30]:
# zeros là hàm tạo 1 array, bao gồm hàng, cột được fill số O
# str : np.zeros(shape, dtype=float, order='C', *, like=None)
np.zeros((2, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
# ones là hàm tạo 1 array, bao gồm hàng, cột được fill số 1
# GẦN TƯƠNG TỰ VỚI ZEROS
# str : np.ones(shape, dtype=None, order='C', *, device=None, like=None)
np.ones((2, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
# full là hàm tạo 1 array, bao gồm hàng, cột được fill bởi số được nhập vào
# str : np.zeros(shape , fill_value,, order='C', *, like=None)
np.full((2,3), 3) # array([[3, 3, 3],
                        #[3, 3, 3]])
np.full((2,3), [1,2,3])

array([[1, 2, 3],
       [1, 2, 3]])

In [44]:
# arange là hàm tạo 1 array,bao gồm số start, số stop - 1 , bước nhảy step ( default 1 )
# str : arange([start,] stop[, step,], dtype=None, *, device=None, like=None)
np.arange(1,10) #array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.arange(1,10, 2) # array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [4]:
# linspace là hàm tạo 1 array,bao gồm số start, số stop, num là số element muốn có (khoảng cách sẽ được chia đều trong khoảng start stop ) 
# str : np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,*,device=None,)
# note : endpoint = True ( tính luôn điểm cuối ) # False
# note : retstep=False ( không hiển thị step ) # True
np.linspace(2, 3, 5) # array([2.  , 2.25, 2.5 , 2.75, 3.  ])
np.linspace(2, 3, 5, endpoint=False) # array([2. , 2.2, 2.4, 2.6, 2.8])
np.linspace(2, 3, 5, retstep = True) # (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

### Ôn tập

### Bài 1 – Tạo và ép kiểu dữ liệu
### Tạo một NumPy array từ danh sách [1, 2, 3, 4.5, 5.7].
### In ra kiểu dữ liệu của mảng (dtype).
### Ép kiểu mảng thành int32 và in ra kết quả.
### Ép kiểu mảng thành str và in ra kết quả.

In [13]:
a1 = np.array([1, 2, 3, 4.5, 5.7])
a1.dtype

a2 = np.array([1, 2, 3, 4.5, 5.7], dtype ="int32")
print(a2)

a3 = np.array([1, 2, 3, 4.5, 5.7], dtype ="str")
print(a3)

[1 2 3 4 5]
['1' '2' '3' '4.5' '5.7']


### Bài 2 Kiểm tra kiểu dữ liệu và thuộc tính. In ra số chiều, kích thước (shape) và tổng số phần tử của arr. Ép kiểu arr thành int32. In ra mảng sau khi ép kiểu.

In [23]:
a = np.array([[1,2,3],
        [4,5,6]], dtype = "float32")

a.shape
a.size


a1= np.array([[1,2,3],
        [4,5,6]], dtype = "int32")
print(a1)

[[1 2 3]
 [4 5 6]]


## Hàm RANDOM()


In [32]:
# Sinh ra 1 array gồm n element hoặc arr gồm mxn element
np.random.random((3,2)) #array([[0.02738739, 0.59470183],
                       # [0.54468397, 0.32986624],
                       # [0.18253066, 0.85874309]])
np.random.random((5)) # array([0.18450086, 0.4648839 , 0.92501515, 0.12440241, 0.32435395])

# rand() tương tự random()

array([0.18450086, 0.4648839 , 0.92501515, 0.12440241, 0.32435395])

In [35]:
# str : normal(loc=0.0, scale=1.0, size=None)
# note : khác với loc của Pandas, loc của NumPy là mean : giá trị trung bình
# scale : độ lệnh chuẩn
# size : kích thước mảng ( n || mxn )
np.random.normal(2, 2, (3,3)) 


array([[ 4.93313122,  4.11960229, -0.57514259],
       [ 3.51981643,  2.73497303,  4.02241195],
       [ 0.7506866 , -0.06274738,  0.92388889]])

In [41]:
# str : randint(low, high=None, size=None, dtype=int)
np.random.randint(2, 10, (3,3))

array([[6, 9, 5],
       [8, 7, 6],
       [4, 9, 9]], dtype=int32)

## Array Indexing & Slicing : tiếp cận element trong arr


In [67]:
# Truy cập element on Array
x = np.random.randint(10, size = (5,5), dtype = int)

In [50]:
x

array([[8, 3, 3],
       [2, 0, 7],
       [2, 4, 2]], dtype=int32)

In [55]:
x[0,2]

np.int32(3)

In [56]:
# thay thế phần tử
x[0,2] = 0
x

array([[8, 3, 0],
       [2, 0, 7],
       [2, 4, 2]], dtype=int32)

### Slicing  : cắt khoảng trong array

In [ ]:
# str x[start : stop : step]
# kết quả trả về là mảng từ start đến stop-1 với step

In [60]:
y = np.random.randint(10, size = 8)

In [61]:
y

array([8, 2, 4, 7, 7, 4, 2, 3], dtype=int32)

In [63]:
# Mảng 1 chiều
y[0:5:2]

array([8, 4, 7], dtype=int32)

In [68]:
#Mảng 2 chiều
# x[row_slice, column_slice]
# chi tiet : x[start_row:end_row:step_row, start_col:end_col:step_col]

x

array([[6, 0, 4, 5, 8],
       [2, 5, 5, 3, 7],
       [3, 0, 5, 4, 6],
       [8, 4, 1, 9, 6],
       [2, 7, 8, 4, 2]], dtype=int32)

In [78]:

x[3:, -1:]

array([[6],
       [2]], dtype=int32)

## Reshaping of Array & Transpose
### Chuyển đổi npArr sang shape khác

### Reshape()

In [28]:
# tạo 1 array bằng random hoặc arrange
grida = np.random.randint(10, size = 9)
grida

gridb = np.arange(1, 10)
gridb



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# str : x.reshape((mxn))
grida.reshape((3,3))
gridb.reshape((3,3))
gridb.shape

(9,)

### Tranpose()

In [128]:
# Reshape chuyển thành hình dạng theo mong muốn
# Tranpose chuyển hàng thành cột và cột thành hàng
# str : a.T
a = np.array([[1,2,3],
              [4,5,6]])

a.T


array([[1, 4],
       [2, 5],
       [3, 6]])

## Array Concatenation and Splitting
### Nối và tách NumPyArray

In [137]:
# str : concatenate( (a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind" )
# axis = 0 thì nối theo 1 hàng, =1 thì nối thêm thành 2 hàng
x = np.array([1,2,3])
y = np.array([4,5,6])

np.concatenate((x,y))



array([1, 2, 3, 4, 5, 6])

In [141]:
#axis=0 → nối dọc (thêm hàng)
#axis=1 → nối ngang (thêm cột) ( chỉ áp dụng được cho mảng 2 chiều ) 
grid = np.array([[1,2,3],
               [4,5,6]])
np.concatenate((grid, grid)) # axis = 0 thì thêm hàng
np.concatenate((grid, grid), axis = 1)  # axis = 1 thì thêm cột 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### vstack() tương tự như axis = 0
### hstack() tương tự như axis = 1

In [146]:
# vstack()
m = np.array([7,8,9])
np.vstack((grid, m)) 
# hstack() 
n = np.array([[7],    
            [8]])
np.hstack((grid,n))

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

### Splitting Array

In [158]:
# str : np.split(ary, indices_or_sections, axis = 0)
# ary : tên array muốn split
# indices_or_sections : khoảng [chi số] muốn cắt, nếu cắt khoảng giữa thì sẽ chia thành 3 array
# có thể gán cho số lượng biến tương tự sau khi cắt
x = np.random.randint(10,size = 8)
a,b,c = np.split(x, [2,6])
print("a la ", a,
     "\n b la " , b,
     "\nc la " , c)

a la  [3 0] 
 b la  [0 3 5 6] 
c la  [6 6]


### Ôn tập : Tạo mảng a có kích thước (4, 5) gồm các số nguyên ngẫu nhiên trong khoảng từ 5 đến 20. In ra mảng a. In ra phần tử ở hàng 2, cột 4. In ra 2 cột đầu tiên của mảng. In ra shape và dtype của a

In [11]:
a = np.random.randint(5,20, size = (4,5))
a

a[2,4]

a[:, 2:]



array([[18, 13, 12],
       [ 9,  7, 16],
       [16, 17, 15],
       [15,  6, 14]], dtype=int32)

### Bài 2 — Dải số & phân phối chuẩn Tạo mảng b = np.linspace(0, 10, 5, endpoint=False, dtype=float) → In ra mảng b. Tạo mảng c = np.random.normal(loc=0, scale=1, size=(2,5)). In ra mảng c. In ra giá trị trung bình (mean) của từng hàng. Nối b (sau khi reshape thành (1,5)) và c theo chiều dọc.

In [43]:
a = np.linspace(0,10,5, endpoint = False, dtype = float)
a
a.shape

(5,)

In [15]:
b = np.random.normal(0,1, size = (2,5))
b.mean()

np.float64(0.16385739261876617)

In [50]:
c = a.reshape(1,5)
z =np.concatenate((c, b))
z

array([[ 0.        ,  2.        ,  4.        ,  6.        ,  8.        ],
       [ 0.43451887,  0.33570374,  1.1529182 , -0.52776215,  0.44961348],
       [-1.11026192,  0.2996984 ,  1.03497523, -0.22804509, -0.20278483]])

### Bài 3 — Ghép và cắt mảng Tạo 2 mảng: x = np.random.randint(1, 10, (3,3)) y = np.random.randint(10, 20, (3,3)) Thực hiện: Nối x và y theo chiều dọc rồi in ra shape của kết quả. Nối x và y theo chiều ngang rồi in ra shape. Từ mảng x, in ra đường chéo chính (gợi ý: np.diag(x)).

In [3]:
x = np.random.randint(1,10, size = (3,3))
y = np.random.randint(10,20, size = (3,3))

In [54]:
x,y

(array([[3, 2, 9],
        [8, 7, 6],
        [4, 6, 1]], dtype=int32),
 array([[17, 16, 17],
        [13, 17, 12],
        [12, 17, 15]], dtype=int32))

In [58]:
doc = np.concatenate((x,y) )
doc

array([[ 3,  2,  9],
       [ 8,  7,  6],
       [ 4,  6,  1],
       [17, 16, 17],
       [13, 17, 12],
       [12, 17, 15]], dtype=int32)

In [4]:
ngang = np.concatenate((x,y), axis = 1)
ngang

array([[ 1,  7,  8, 12, 16, 18],
       [ 6,  7,  5, 18, 18, 15],
       [ 1,  8,  8, 19, 16, 13]], dtype=int32)

In [9]:
x

array([[5, 2, 8],
       [9, 6, 9],
       [1, 3, 7]], dtype=int32)

In [5]:
ngang

array([[ 1,  7,  8, 12, 16, 18],
       [ 6,  7,  5, 18, 18, 15],
       [ 1,  8,  8, 19, 16, 13]], dtype=int32)

## Broadcasting and Vectorized operations

### Broadcasting : cộng, trừ,... 2 mảng giống hoặc khác size

In [3]:
a = np.arange(3)

In [4]:
a

array([0, 1, 2])

In [6]:
# Cộng mảng a size(3.) với số 5 size(1,) thì số 5 sẽ tự generate ra thành mảng [5,5,5]
a + 5

array([5, 6, 7])

In [8]:
b = np.arange(3,9)

In [11]:
b *5

array([15, 20, 25, 30, 35, 40])